name: 'Kotlin Script'
description: 'Run a Kotlin script'

branding:
  icon: 'code'
  color: 'blue'
  
inputs:
  script:
    description: 'Script to execute'
    required: false
    default: ''
  file:
    description: 'kts file to run'
    required: false
    default: 'default.main.kts'
    
runs:
  using: "composite"
  steps:
    - name: Generate script file
      if: ${{ inputs.script != '' }}
      run: |
        echo "#!/usr/bin/env kotlin" >> ${{ inputs.file }}
        SCRIPT=${{ inputs.script }}
        echo ${SCRIPT@Q} >> ${{ inputs.file }}
        chmod +x ${{ inputs.file }}
      shell: bash
    
    - name: Validate file
      if: ${{ inputs.script != '' }}
      run: |
        ls -a
        cat ${{ inputs.file }}
      shell: bash
    
    - name: Run Kotlin script
      run: kotlinc -script ./${{ inputs.file }}
      shell: bash
     
