name: Test Kotlin Script

on:
  workflow_dispatch:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run simple script
        uses: ./
        with:
          script: |
            println("hello world")
